version: "2"
run:
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - depguard
    - exhaustive
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - revive
    - staticcheck
    - unparam
    - unused
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - '!$test'
          deny:
            - pkg: io/ioutil
              desc: this is deprecated
    gocyclo:
      min-complexity: 25
    gosec:
      excludes:
        - G104  # unhandled errors - acceptable for cache warming
        - G304  # file inclusion via variable - intentional config loading
        - G404  # weak random - only used for test IDs
        - G601
    lll:
      line-length: 130
    revive:
      severity: warning
      rules:
        - name: blank-imports
          severity: warning
        - name: context-as-argument
        - name: context-keys-type
        - name: duplicated-imports
        - name: error-naming
        - name: error-return
        - name: exported
          disabled: true
        - name: if-return
        - name: identical-branches
        - name: indent-error-flow
        - name: import-shadowing
        - name: package-comments
          disabled: true
        - name: redefines-builtin-id
        - name: struct-tag
        - name: unconditional-recursion
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
          disabled: true
        - name: unhandled-error
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
          - gocyclo
          - errcheck
          - dupl
          - gosec
        path: (.+)_test\.go
      - linters:
          - lll
        path: .golangci.yml
      - linters:
          - govet
        text: "unsafeptr"
        path: internal/wm/
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/machina/mosaico)
  exclusions:
    generated: lax
